all:
  children:
    pi:
      hosts:
        pi5:
          ansible_host: 172.42.42.2
          ansible_user: homelab

    radxa:
      hosts:
        q6a:
          ansible_host: 172.42.42.1
          ansible_user: homelab
